[package]
name = "endocing_detector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.33"
clap = "4.5.4"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
